# Simple workflow for deploying static content to GitHub Pages
name: Build docs

on:
    workflow_dispatch:
    workflow_call:
    pull_request:
      branches:
        - main

env:
  # `BASE_URL` determines the website is served from, including CSS & JS assets
  # You may need to change this to `BASE_URL: ''`
  BASE_URL: /${{ github.event.repository.name }}

jobs:
  build-docs:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/scientificcomputing/latex-full:2023-11-07a
    env:
      PUBLISH_DIR: ./book/_build/html

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: python3 -m pip install .

      - name: Build pdfs
        run: cd book && myst build --pdf

      - name: Merge pdfs
        run: python3 merge-abstracts.py

      - name: Build HTML
        run: cd book && myst build --html

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: ${{ env.PUBLISH_DIR }}
