# Simple workflow for deploying static content to GitHub Pages
name: Reproduce results


on:
  workflow_dispatch:
  workflow_call:


jobs:
  fake-abstracts:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: python3 -m pip install .

      - name: Run pre-processing cylinder
        run: python3 generate_fake_abstracts.py abstracts.csv 10


      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          path: ./abstracts.csv
          name: abstracts
          if-no-files-found: error
